"""add director to the cinema

Revision ID: 61d8f735fe4e
Revises: 2dd8260ad2ec
Create Date: 2025-08-21 17:53:06.093677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d8f735fe4e'
down_revision = '2dd8260ad2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('director', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'director')
    # ### end Alembic commands ###
