"""add plot to cinema

Revision ID: 2dd8260ad2ec
Revises: 0fd2816303d6
Create Date: 2025-08-21 17:47:07.360359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd8260ad2ec'
down_revision = '0fd2816303d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('plot', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'plot')
    # ### end Alembic commands ###
