"""update tables

Revision ID: 978fdc4e6c23
Revises: b9e391dedee6
Create Date: 2025-08-21 13:36:00.636370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978fdc4e6c23'
down_revision = 'b9e391dedee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_genres', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_genres', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
